<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="4242" started-at="2018-05-10T05:54:36Z" finished-at="2018-05-10T05:54:40Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="4242" started-at="2018-05-10T05:54:36Z" finished-at="2018-05-10T05:54:40Z">
      <class name="pri.study.timeout.Timeout">
        <test-method status="FAIL" signature="testFailed()[pri:0, instance:pri.study.timeout.Timeout@c0edeb]" name="testFailed" duration-ms="2161" started-at="2018-05-10T05:54:36Z" finished-at="2018-05-10T05:54:38Z">
          <exception class="org.testng.internal.thread.ThreadTimeoutException">
            <message>
              <![CDATA[Method pri.study.timeout.Timeout.testFailed() didn't finish within the time-out 2000]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method pri.study.timeout.Timeout.testFailed() didn't finish within the time-out 2000
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.internal.thread.ThreadTimeoutException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testFailed -->
        <test-method status="PASS" signature="testSuccess()[pri:0, instance:pri.study.timeout.Timeout@c0edeb]" name="testSuccess" duration-ms="2004" started-at="2018-05-10T05:54:38Z" finished-at="2018-05-10T05:54:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSuccess -->
      </class> <!-- pri.study.timeout.Timeout -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
